In [1]:
# Import Dependencies
from faker import Faker
import random
import pandas as pd
from datetime import datetime, timedelta

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [8]:
# Load existing data
existing_data = pd.read_csv('/Users/galbeeir/Desktop/git/Project 4 - Fradulent Transactions/fraudulent_transactions/ML_and_dashboard/datagen/CSVs/fraudTest.csv')

# * Initialize Faker
fake = Faker()

#NOTE: Number of rows to generate
num_rows = 1000 

#NOTE: Define the daterange
start_date = datetime(2022, 1, 1)  # * Change this to your desired start date
end_date = datetime(2023, 1, 1)    # * Change this to your desired end date

# * Generate Random Data Set
data = []
last_fraud_transaction_time = None

for _ in range(num_rows):
    # * Generate a random age between 18 and 90
    age = random.randint(18, 90)
    
    # * Calculate date of birth based on the random age
    dob = (datetime.now() - timedelta(days=age*365)).strftime('%d/%m/%Y')
    
    # * Generate a random number of days between start_date and end_date
    random_days = random.randint(0, (end_date - start_date).days)
    
    # * Calculate transaction time within the date range
    transaction_time = start_date + timedelta(days=random_days)
    
    # * Generating a fraudulent transaction every 7 days
    if last_fraud_transaction_time is None or (transaction_time - last_fraud_transaction_time).days >= 7:
        is_fraud = 1
        last_fraud_transaction_time = transaction_time
    else:
        is_fraud = 0
    
    row = [
        transaction_time.strftime('%d/%m/%Y %H:%M'),  #? trans_date_&_time
        fake.credit_card_number(card_type='mastercard'),  #? cc_num
        fake.company(),  #? merchant
        fake.random_element(existing_data['category']),  #? category
        round(random.uniform(1.0, 200.0), 2),  #? amt
        fake.first_name(),  #? first
        fake.last_name(),  #? last
        fake.random_element(['M', 'F']),  #? gender
        fake.street_address(),  #? street
        fake.city(),  #? city
        fake.state(),  #? state
        fake.zipcode(),  #? zip
        round(random.uniform(25.0, 50.0), 4),  #? lat
        round(random.uniform(-125.0, -66.0), 4),  #? long
        random.randint(1000, 100000),  #? city_pop
        fake.job(),  #? job
        dob,  #? dob
        fake.uuid4(),  # trans_num
        int(transaction_time.timestamp()),  #? unix_time
        round(random.uniform(25.0, 50.0), 4),  #? merch_lat
        round(random.uniform(-125.0, -66.0), 4),  #? merch_long
        is_fraud  #? is_fraud
    ]
    data.append(row)

#NOTE: Generate list of columns based on the existing data
columns = list(existing_data.columns[1:])

#NOTE: Create a DataFrame based on the data & columns variables
df = pd.DataFrame(data, columns=columns)
# fraud_column = pd.Series(data, name='is_fraud')

# # Show the DataFrame head
# fraud_column

In [11]:
sampled_dfs = [s.sample(n=300, random_state=2023) for s in df]

AttributeError: 'str' object has no attribute 'sample'

In [17]:
# List comprehension to create samples
samples = [df.sample(n=300, random_state=2023) for _ in range(3)]
samples[2]

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
847,18/06/2022 00:00,5569859165868341,"Pearson, Brown and Vasquez",entertainment,94.28,Rhonda,Munoz,F,80605 Daniel Spurs,North Deanberg,...,41.4235,-94.2819,45424,"Administrator, local government",19/11/1953,b131c628-26bd-4222-9b88-a2cd93b440ae,1655474400,34.0559,-94.9469,0
874,21/10/2022 00:00,5233116640668424,"Mcdaniel, Reese and Hopkins",kids_pets,175.22,Matthew,Williams,M,1657 Jones Flats Apt. 546,Port Andreafurt,...,37.0672,-108.8771,30956,Financial manager,23/11/1938,6acaa851-6952-469a-a0f2-3c3fed7d23fa,1666270800,35.4382,-106.2793,0
471,15/04/2022 00:00,5483604526409838,"Gentry, Simon and Velazquez",kids_pets,94.24,Angela,Greene,M,22027 Smith Glen Apt. 948,East Renee,...,41.9789,-121.1808,93469,Psychiatric nurse,23/11/1937,235c65fc-63f3-43ab-acbe-9f5c7c14e6ed,1649944800,49.6078,-95.0015,0
476,24/11/2022 00:00,5201734886645357,Moore Group,grocery_pos,182.28,Paul,Bautista,F,459 Sara Forge Suite 135,Johnsonberg,...,33.5381,-88.5260,5402,Publishing copy,10/11/1989,3c32d908-b58c-4f4f-8894-5fef54166299,1669208400,32.6065,-88.7052,0
764,11/12/2022 00:00,5213655940526273,Barrett-Holmes,health_fitness,139.06,Angela,Alexander,F,76526 Lisa Ridges Suite 358,Bullockberg,...,49.3675,-68.4445,76986,Public relations account executive,17/11/1961,be8615bd-6ebe-4ef6-87c6-a55d8953c1cb,1670677200,35.2484,-73.2333,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,12/02/2022 00:00,5407613587297456,"Stafford, Johnson and Doyle",gas_transport,161.19,Dawn,Mcclure,F,252 Ross Isle Suite 581,South Christophertown,...,44.6645,-79.5812,79530,"Engineer, automotive",09/11/1994,00c6743d-2bf1-4cf3-910e-cfdc66e65e20,1644584400,37.7279,-99.0120,0
236,13/05/2022 00:00,5424732396345345,Harrell Inc,entertainment,62.60,Logan,Holmes,F,5225 Davis Ford,Danielshire,...,44.1218,-90.1646,77764,"Surveyor, rural practice",12/11/1980,2e6a10b0-6209-4d1f-bc2f-315c7db75903,1652364000,29.8917,-106.6615,0
581,01/07/2022 00:00,5269470609360722,Arroyo-Wallace,misc_pos,110.01,Robert,Wallace,F,76525 Alvarado Mountains Apt. 785,East Jonathanmouth,...,39.7622,-118.2062,4223,Office manager,13/11/1979,ceaa7328-bf23-4df4-b528-978d5545fc8a,1656597600,30.9850,-83.1681,0
324,21/06/2022 00:00,5418426605372806,Whitaker LLC,home,140.94,Kevin,James,F,7923 Kevin Forks,Barnesmouth,...,35.1338,-123.0375,33768,"Therapist, music",24/11/1934,10cb77e4-88c2-44ed-865b-0026ccecbf22,1655733600,42.9748,-77.7299,0
988,21/11/2022 00:00,5239530487721019,"Cuevas, Wilson and Walker",entertainment,80.38,Brian,Fuller,M,0443 Johnson Dale Suite 119,Roberthaven,...,45.3646,-106.8325,58722,Health visitor,12/11/1980,5797c661-20b1-4619-8e12-bafd070a821c,1668949200,46.5786,-67.2370,0

In [4]:
# Show the proportion of the fradulant and non-fradulant transactions
df['is_fraud'].value_counts()

0    992
1      8
Name: is_fraud, dtype: int64

In [5]:
df['is_fraud'].value_counts(normalize=True)

0    0.992
1    0.008
Name: is_fraud, dtype: float64